/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ArtworksRouteImport } from './routes/artworks'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsRetaingraphRouteImport } from './routes/projects_.retaingraph'
import { Route as ProjectsPolarisRouteImport } from './routes/projects_.polaris'
import { Route as ProjectsOvelaRouteImport } from './routes/projects_.ovela'
import { Route as ProjectsNavswapRouteImport } from './routes/projects_.navswap'
import { Route as ProjectsCortexRouteImport } from './routes/projects_.cortex'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ArtworksRoute = ArtworksRouteImport.update({
  id: '/artworks',
  path: '/artworks',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRetaingraphRoute = ProjectsRetaingraphRouteImport.update({
  id: '/projects_/retaingraph',
  path: '/projects/retaingraph',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsPolarisRoute = ProjectsPolarisRouteImport.update({
  id: '/projects_/polaris',
  path: '/projects/polaris',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsOvelaRoute = ProjectsOvelaRouteImport.update({
  id: '/projects_/ovela',
  path: '/projects/ovela',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsNavswapRoute = ProjectsNavswapRouteImport.update({
  id: '/projects_/navswap',
  path: '/projects/navswap',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsCortexRoute = ProjectsCortexRouteImport.update({
  id: '/projects_/cortex',
  path: '/projects/cortex',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/artworks': typeof ArtworksRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects/cortex': typeof ProjectsCortexRoute
  '/projects/navswap': typeof ProjectsNavswapRoute
  '/projects/ovela': typeof ProjectsOvelaRoute
  '/projects/polaris': typeof ProjectsPolarisRoute
  '/projects/retaingraph': typeof ProjectsRetaingraphRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/artworks': typeof ArtworksRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects/cortex': typeof ProjectsCortexRoute
  '/projects/navswap': typeof ProjectsNavswapRoute
  '/projects/ovela': typeof ProjectsOvelaRoute
  '/projects/polaris': typeof ProjectsPolarisRoute
  '/projects/retaingraph': typeof ProjectsRetaingraphRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/artworks': typeof ArtworksRoute
  '/contact': typeof ContactRoute
  '/projects': typeof ProjectsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/projects_/cortex': typeof ProjectsCortexRoute
  '/projects_/navswap': typeof ProjectsNavswapRoute
  '/projects_/ovela': typeof ProjectsOvelaRoute
  '/projects_/polaris': typeof ProjectsPolarisRoute
  '/projects_/retaingraph': typeof ProjectsRetaingraphRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/artworks'
    | '/contact'
    | '/projects'
    | '/sitemap.xml'
    | '/projects/cortex'
    | '/projects/navswap'
    | '/projects/ovela'
    | '/projects/polaris'
    | '/projects/retaingraph'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/artworks'
    | '/contact'
    | '/projects'
    | '/sitemap.xml'
    | '/projects/cortex'
    | '/projects/navswap'
    | '/projects/ovela'
    | '/projects/polaris'
    | '/projects/retaingraph'
  id:
    | '__root__'
    | '/'
    | '/artworks'
    | '/contact'
    | '/projects'
    | '/sitemap.xml'
    | '/projects_/cortex'
    | '/projects_/navswap'
    | '/projects_/ovela'
    | '/projects_/polaris'
    | '/projects_/retaingraph'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ArtworksRoute: typeof ArtworksRoute
  ContactRoute: typeof ContactRoute
  ProjectsRoute: typeof ProjectsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ProjectsCortexRoute: typeof ProjectsCortexRoute
  ProjectsNavswapRoute: typeof ProjectsNavswapRoute
  ProjectsOvelaRoute: typeof ProjectsOvelaRoute
  ProjectsPolarisRoute: typeof ProjectsPolarisRoute
  ProjectsRetaingraphRoute: typeof ProjectsRetaingraphRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/artworks': {
      id: '/artworks'
      path: '/artworks'
      fullPath: '/artworks'
      preLoaderRoute: typeof ArtworksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/retaingraph': {
      id: '/projects_/retaingraph'
      path: '/projects/retaingraph'
      fullPath: '/projects/retaingraph'
      preLoaderRoute: typeof ProjectsRetaingraphRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/polaris': {
      id: '/projects_/polaris'
      path: '/projects/polaris'
      fullPath: '/projects/polaris'
      preLoaderRoute: typeof ProjectsPolarisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/ovela': {
      id: '/projects_/ovela'
      path: '/projects/ovela'
      fullPath: '/projects/ovela'
      preLoaderRoute: typeof ProjectsOvelaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/navswap': {
      id: '/projects_/navswap'
      path: '/projects/navswap'
      fullPath: '/projects/navswap'
      preLoaderRoute: typeof ProjectsNavswapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/cortex': {
      id: '/projects_/cortex'
      path: '/projects/cortex'
      fullPath: '/projects/cortex'
      preLoaderRoute: typeof ProjectsCortexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ArtworksRoute: ArtworksRoute,
  ContactRoute: ContactRoute,
  ProjectsRoute: ProjectsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ProjectsCortexRoute: ProjectsCortexRoute,
  ProjectsNavswapRoute: ProjectsNavswapRoute,
  ProjectsOvelaRoute: ProjectsOvelaRoute,
  ProjectsPolarisRoute: ProjectsPolarisRoute,
  ProjectsRetaingraphRoute: ProjectsRetaingraphRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
